version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Puerto para la comunicaci칩n de los microservicios
      - "15672:15672"  # Puerto para la consola de administraci칩n
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
    - custom-network

  ms-clients:
    build:
      context: ./ms-clients   # Ruta donde est치 el Dockerfile del Microservicio 1
      dockerfile: Dockerfile
    container_name: ms-clients
    ports:
      - "8081:8081"           # Puerto del Microservicio 1
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
    depends_on:
      - rabbitmq
    networks:
    - custom-network

  ms-accounts-trxs:
    build:
      context: ./ms-accounts-trxs  # Ruta donde est치 el Dockerfile del Microservicio 2
      dockerfile: Dockerfile
    container_name: ms-accounts
    ports:
      - "8082:8082"           # Puerto del Microservicio 2
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
    depends_on:
      - rabbitmq
    networks:
    - custom-network

networks:
  custom-network:
    driver: bridge    
